### ISSUE TITLE
modelnet40 dataset

### ISSUE THREAD

**Issue by Faye0123** [WordBearerYI/Unsupervised-Deep-Shape-Descriptor-with-Point-Distribution-Learning#3]
Hi! Thanks for sharing this project.
The provided link for modelnet40 dataset is not accessible.
Could you suggest where can I get it?
Thanks

**Comment by Yi-Shi94** [comment]
Hello, the aligned version of modelnet40 is provided by Princeton. I downloaded tha data at https://modelnet.cs.princeton.edu/
